apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: olympus-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.13.1-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          volumeMounts:
            - name: nginx-conf
              readOnly: true
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: nginx-conf
          configMap:
            name: olympus-nginx-conf
