apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: olympus-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: olympus
    spec:
      containers:
        - name: olympus-app
          image: marselester/olympus:v1.0.0
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          # livenessProbe is to check whether container is alive.
          # When container is unhealthy, it will be restarted.
          livenessProbe:
            exec:
              command:
                - curl
                - "http://localhost/healthz"
                - --fail
            initialDelaySeconds: 1
            timeoutSeconds: 1
          # readinessProbe determines whether app is able to serve requests.
          # If it's not ready yet, the container won't receive traffic
          # through Kubernetes Services.
          readinessProbe:
            exec:
              command:
                - curl
                - "http://localhost/healthz"
                - --fail
            initialDelaySeconds: 1
            timeoutSeconds: 1

        - name: statsd-exporter
          image: prom/statsd-exporter:latest
          ports:
            - containerPort: 9102
          args:
            - "-statsd.listen-address=localhost:8125"
